services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./
      target: development
    entrypoint: ./docker-compose/development-entrypoint.sh
    container_name: daybound-app
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/usr/src/daybound
    ports:
      - 3000:3000
