FROM node:24-alpine AS base

WORKDIR /usr/src/web

COPY ./web ./
COPY ./docker-compose ./docker-compose

RUN corepack enable && \
    yarn install && \
    # Fixing permissions on all files
    chown -R node:node ./ && \
    chmod -R 755 ./

USER node

FROM base AS development

CMD ["yarn", "run", "dev", "--host", "0.0.0.0"]

FROM base AS production

RUN yarn run build

CMD ["yarn", "run", "preview", "--host", "0.0.0.0"]
