services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./
      target: development
    entrypoint: ./docker-compose/development-entrypoint.sh
    container_name: daybound-app
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/usr/src/daybound
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mariadb:11.4.10
    container_name: daybound-database
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - daybound-database:/var/lib/mysql/
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

volumes:
  daybound-database:
